# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-25 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangopay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangoPayPayInWeb',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('mangopay.mangopaypayin',),
        ),
        migrations.AddField(
            model_name='mangopaypayin',
            name='culture',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='mangopaypayin',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mangopaypayin',
            name='return_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
