# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-22 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mangopay', '0002_auto_20160725_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangopaybankaccount',
            name='address',
        ),
        migrations.AddField(
            model_name='mangopaybankaccount',
            name='address_line_1',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mangopaybankaccount',
            name='address_line_2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mangopaybankaccount',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mangopaybankaccount',
            name='owner_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mangopaybankaccount',
            name='postal_code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mangopaybankaccount',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mangopaybankaccount',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
